/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as ProphetsIndexRouteImport } from './routes/prophets.index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as HadithIndexRouteImport } from './routes/hadith.index'
import { Route as EmotionsIndexRouteImport } from './routes/emotions.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as SurahIdRouteImport } from './routes/surah.$id'
import { Route as ProphetsSlugRouteImport } from './routes/prophets.$slug'
import { Route as PlansSlugRouteImport } from './routes/plans.$slug'
import { Route as LearnGraphRouteImport } from './routes/learn.graph'
import { Route as KnowledgeHadithRouteImport } from './routes/knowledge.hadith'
import { Route as HadithTopicsRouteImport } from './routes/hadith.topics'
import { Route as HadithNarratorsRouteImport } from './routes/hadith.narrators'
import { Route as HadithMuslimRouteImport } from './routes/hadith.muslim'
import { Route as HadithBukhariRouteImport } from './routes/hadith.bukhari'
import { Route as HadithCollectionRouteImport } from './routes/hadith.$collection'
import { Route as ExploreTimelineRouteImport } from './routes/explore.timeline'
import { Route as ExploreMapRouteImport } from './routes/explore.map'
import { Route as EmotionsSlugRouteImport } from './routes/emotions.$slug'
import { Route as LearnJourneysIndexRouteImport } from './routes/learn.journeys.index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections.index'
import { Route as LearnJourneysSlugRouteImport } from './routes/learn.journeys.$slug'
import { Route as LearnKindSlugRouteImport } from './routes/learn.$kind.$slug'
import { Route as HadithCollectionNumRouteImport } from './routes/hadith.$collection.$num'
import { Route as HadithCollectionBookRouteImport } from './routes/hadith.$collection.$book'
import { Route as ApiPublicSeedKnowledgeRouteImport } from './routes/api/public/seed-knowledge'
import { Route as ApiPublicAdminTranslateTafsirHebrewRouteImport } from './routes/api/public/admin/translate-tafsir-hebrew'
import { Route as ApiPublicAdminRebuildGroundedIndexRouteImport } from './routes/api/public/admin/rebuild-grounded-index'
import { Route as ApiPublicAdminEmbedHadithRouteImport } from './routes/api/public/admin/embed-hadith'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/research.lazy').then((d) => d.Route))
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ask.lazy').then((d) => d.Route))
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphetsIndexRoute = ProphetsIndexRouteImport.update({
  id: '/prophets/',
  path: '/prophets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithIndexRoute = HadithIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HadithRoute,
} as any)
const EmotionsIndexRoute = EmotionsIndexRouteImport.update({
  id: '/emotions/',
  path: '/emotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/surah/$id',
  path: '/surah/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphetsSlugRoute = ProphetsSlugRouteImport.update({
  id: '/prophets/$slug',
  path: '/prophets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansSlugRoute = PlansSlugRouteImport.update({
  id: '/plans/$slug',
  path: '/plans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGraphRoute = LearnGraphRouteImport.update({
  id: '/learn/graph',
  path: '/learn/graph',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/learn.graph.lazy').then((d) => d.Route))
const KnowledgeHadithRoute = KnowledgeHadithRouteImport.update({
  id: '/knowledge/hadith',
  path: '/knowledge/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithTopicsRoute = HadithTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => HadithRoute,
} as any)
const HadithNarratorsRoute = HadithNarratorsRouteImport.update({
  id: '/narrators',
  path: '/narrators',
  getParentRoute: () => HadithRoute,
} as any)
const HadithMuslimRoute = HadithMuslimRouteImport.update({
  id: '/muslim',
  path: '/muslim',
  getParentRoute: () => HadithRoute,
} as any)
const HadithBukhariRoute = HadithBukhariRouteImport.update({
  id: '/bukhari',
  path: '/bukhari',
  getParentRoute: () => HadithRoute,
} as any)
const HadithCollectionRoute = HadithCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => HadithRoute,
} as any)
const ExploreTimelineRoute = ExploreTimelineRouteImport.update({
  id: '/explore/timeline',
  path: '/explore/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMapRoute = ExploreMapRouteImport.update({
  id: '/explore/map',
  path: '/explore/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionsSlugRoute = EmotionsSlugRouteImport.update({
  id: '/emotions/$slug',
  path: '/emotions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJourneysIndexRoute = LearnJourneysIndexRouteImport.update({
  id: '/learn/journeys/',
  path: '/learn/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LearnJourneysSlugRoute = LearnJourneysSlugRouteImport.update({
  id: '/learn/journeys/$slug',
  path: '/learn/journeys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnKindSlugRoute = LearnKindSlugRouteImport.update({
  id: '/learn/$kind/$slug',
  path: '/learn/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithCollectionNumRoute = HadithCollectionNumRouteImport.update({
  id: '/$num',
  path: '/$num',
  getParentRoute: () => HadithCollectionRoute,
} as any)
const HadithCollectionBookRoute = HadithCollectionBookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => HadithCollectionRoute,
} as any)
const ApiPublicSeedKnowledgeRoute = ApiPublicSeedKnowledgeRouteImport.update({
  id: '/api/public/seed-knowledge',
  path: '/api/public/seed-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminTranslateTafsirHebrewRoute =
  ApiPublicAdminTranslateTafsirHebrewRouteImport.update({
    id: '/api/public/admin/translate-tafsir-hebrew',
    path: '/api/public/admin/translate-tafsir-hebrew',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminRebuildGroundedIndexRoute =
  ApiPublicAdminRebuildGroundedIndexRouteImport.update({
    id: '/api/public/admin/rebuild-grounded-index',
    path: '/api/public/admin/rebuild-grounded-index',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminEmbedHadithRoute =
  ApiPublicAdminEmbedHadithRouteImport.update({
    id: '/api/public/admin/embed-hadith',
    path: '/api/public/admin/embed-hadith',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emotions/$slug': typeof EmotionsSlugRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/timeline': typeof ExploreTimelineRoute
  '/hadith/$collection': typeof HadithCollectionRouteWithChildren
  '/hadith/bukhari': typeof HadithBukhariRoute
  '/hadith/muslim': typeof HadithMuslimRoute
  '/hadith/narrators': typeof HadithNarratorsRoute
  '/hadith/topics': typeof HadithTopicsRoute
  '/knowledge/hadith': typeof KnowledgeHadithRoute
  '/learn/graph': typeof LearnGraphRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/prophets/$slug': typeof ProphetsSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/emotions/': typeof EmotionsIndexRoute
  '/hadith/': typeof HadithIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/prophets/': typeof ProphetsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
  '/hadith/$collection/$book': typeof HadithCollectionBookRoute
  '/hadith/$collection/$num': typeof HadithCollectionNumRoute
  '/learn/$kind/$slug': typeof LearnKindSlugRoute
  '/learn/journeys/$slug': typeof LearnJourneysSlugRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/learn/journeys/': typeof LearnJourneysIndexRoute
  '/api/public/admin/embed-hadith': typeof ApiPublicAdminEmbedHadithRoute
  '/api/public/admin/rebuild-grounded-index': typeof ApiPublicAdminRebuildGroundedIndexRoute
  '/api/public/admin/translate-tafsir-hebrew': typeof ApiPublicAdminTranslateTafsirHebrewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emotions/$slug': typeof EmotionsSlugRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/timeline': typeof ExploreTimelineRoute
  '/hadith/$collection': typeof HadithCollectionRouteWithChildren
  '/hadith/bukhari': typeof HadithBukhariRoute
  '/hadith/muslim': typeof HadithMuslimRoute
  '/hadith/narrators': typeof HadithNarratorsRoute
  '/hadith/topics': typeof HadithTopicsRoute
  '/knowledge/hadith': typeof KnowledgeHadithRoute
  '/learn/graph': typeof LearnGraphRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/prophets/$slug': typeof ProphetsSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/emotions': typeof EmotionsIndexRoute
  '/hadith': typeof HadithIndexRoute
  '/learn': typeof LearnIndexRoute
  '/plans': typeof PlansIndexRoute
  '/prophets': typeof ProphetsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
  '/hadith/$collection/$book': typeof HadithCollectionBookRoute
  '/hadith/$collection/$num': typeof HadithCollectionNumRoute
  '/learn/$kind/$slug': typeof LearnKindSlugRoute
  '/learn/journeys/$slug': typeof LearnJourneysSlugRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/learn/journeys': typeof LearnJourneysIndexRoute
  '/api/public/admin/embed-hadith': typeof ApiPublicAdminEmbedHadithRoute
  '/api/public/admin/rebuild-grounded-index': typeof ApiPublicAdminRebuildGroundedIndexRoute
  '/api/public/admin/translate-tafsir-hebrew': typeof ApiPublicAdminTranslateTafsirHebrewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emotions/$slug': typeof EmotionsSlugRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/timeline': typeof ExploreTimelineRoute
  '/hadith/$collection': typeof HadithCollectionRouteWithChildren
  '/hadith/bukhari': typeof HadithBukhariRoute
  '/hadith/muslim': typeof HadithMuslimRoute
  '/hadith/narrators': typeof HadithNarratorsRoute
  '/hadith/topics': typeof HadithTopicsRoute
  '/knowledge/hadith': typeof KnowledgeHadithRoute
  '/learn/graph': typeof LearnGraphRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/prophets/$slug': typeof ProphetsSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/emotions/': typeof EmotionsIndexRoute
  '/hadith/': typeof HadithIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/prophets/': typeof ProphetsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
  '/hadith/$collection/$book': typeof HadithCollectionBookRoute
  '/hadith/$collection/$num': typeof HadithCollectionNumRoute
  '/learn/$kind/$slug': typeof LearnKindSlugRoute
  '/learn/journeys/$slug': typeof LearnJourneysSlugRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/learn/journeys/': typeof LearnJourneysIndexRoute
  '/api/public/admin/embed-hadith': typeof ApiPublicAdminEmbedHadithRoute
  '/api/public/admin/rebuild-grounded-index': typeof ApiPublicAdminRebuildGroundedIndexRoute
  '/api/public/admin/translate-tafsir-hebrew': typeof ApiPublicAdminTranslateTafsirHebrewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth'
    | '/favorites'
    | '/hadith'
    | '/onboarding'
    | '/profile'
    | '/research'
    | '/search'
    | '/sitemap.xml'
    | '/emotions/$slug'
    | '/explore/map'
    | '/explore/timeline'
    | '/hadith/$collection'
    | '/hadith/bukhari'
    | '/hadith/muslim'
    | '/hadith/narrators'
    | '/hadith/topics'
    | '/knowledge/hadith'
    | '/learn/graph'
    | '/plans/$slug'
    | '/prophets/$slug'
    | '/surah/$id'
    | '/topics/$slug'
    | '/emotions/'
    | '/hadith/'
    | '/learn/'
    | '/plans/'
    | '/prophets/'
    | '/topics/'
    | '/api/public/seed-knowledge'
    | '/hadith/$collection/$book'
    | '/hadith/$collection/$num'
    | '/learn/$kind/$slug'
    | '/learn/journeys/$slug'
    | '/collections/'
    | '/learn/journeys/'
    | '/api/public/admin/embed-hadith'
    | '/api/public/admin/rebuild-grounded-index'
    | '/api/public/admin/translate-tafsir-hebrew'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth'
    | '/favorites'
    | '/onboarding'
    | '/profile'
    | '/research'
    | '/search'
    | '/sitemap.xml'
    | '/emotions/$slug'
    | '/explore/map'
    | '/explore/timeline'
    | '/hadith/$collection'
    | '/hadith/bukhari'
    | '/hadith/muslim'
    | '/hadith/narrators'
    | '/hadith/topics'
    | '/knowledge/hadith'
    | '/learn/graph'
    | '/plans/$slug'
    | '/prophets/$slug'
    | '/surah/$id'
    | '/topics/$slug'
    | '/emotions'
    | '/hadith'
    | '/learn'
    | '/plans'
    | '/prophets'
    | '/topics'
    | '/api/public/seed-knowledge'
    | '/hadith/$collection/$book'
    | '/hadith/$collection/$num'
    | '/learn/$kind/$slug'
    | '/learn/journeys/$slug'
    | '/collections'
    | '/learn/journeys'
    | '/api/public/admin/embed-hadith'
    | '/api/public/admin/rebuild-grounded-index'
    | '/api/public/admin/translate-tafsir-hebrew'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ask'
    | '/auth'
    | '/favorites'
    | '/hadith'
    | '/onboarding'
    | '/profile'
    | '/research'
    | '/search'
    | '/sitemap.xml'
    | '/emotions/$slug'
    | '/explore/map'
    | '/explore/timeline'
    | '/hadith/$collection'
    | '/hadith/bukhari'
    | '/hadith/muslim'
    | '/hadith/narrators'
    | '/hadith/topics'
    | '/knowledge/hadith'
    | '/learn/graph'
    | '/plans/$slug'
    | '/prophets/$slug'
    | '/surah/$id'
    | '/topics/$slug'
    | '/emotions/'
    | '/hadith/'
    | '/learn/'
    | '/plans/'
    | '/prophets/'
    | '/topics/'
    | '/api/public/seed-knowledge'
    | '/hadith/$collection/$book'
    | '/hadith/$collection/$num'
    | '/learn/$kind/$slug'
    | '/learn/journeys/$slug'
    | '/_authenticated/collections/'
    | '/learn/journeys/'
    | '/api/public/admin/embed-hadith'
    | '/api/public/admin/rebuild-grounded-index'
    | '/api/public/admin/translate-tafsir-hebrew'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  HadithRoute: typeof HadithRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResearchRoute: typeof ResearchRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EmotionsSlugRoute: typeof EmotionsSlugRoute
  ExploreMapRoute: typeof ExploreMapRoute
  ExploreTimelineRoute: typeof ExploreTimelineRoute
  KnowledgeHadithRoute: typeof KnowledgeHadithRoute
  LearnGraphRoute: typeof LearnGraphRoute
  PlansSlugRoute: typeof PlansSlugRoute
  ProphetsSlugRoute: typeof ProphetsSlugRoute
  SurahIdRoute: typeof SurahIdRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  EmotionsIndexRoute: typeof EmotionsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  ProphetsIndexRoute: typeof ProphetsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  ApiPublicSeedKnowledgeRoute: typeof ApiPublicSeedKnowledgeRoute
  LearnKindSlugRoute: typeof LearnKindSlugRoute
  LearnJourneysSlugRoute: typeof LearnJourneysSlugRoute
  LearnJourneysIndexRoute: typeof LearnJourneysIndexRoute
  ApiPublicAdminEmbedHadithRoute: typeof ApiPublicAdminEmbedHadithRoute
  ApiPublicAdminRebuildGroundedIndexRoute: typeof ApiPublicAdminRebuildGroundedIndexRoute
  ApiPublicAdminTranslateTafsirHebrewRoute: typeof ApiPublicAdminTranslateTafsirHebrewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophets/': {
      id: '/prophets/'
      path: '/prophets'
      fullPath: '/prophets/'
      preLoaderRoute: typeof ProphetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/': {
      id: '/hadith/'
      path: '/'
      fullPath: '/hadith/'
      preLoaderRoute: typeof HadithIndexRouteImport
      parentRoute: typeof HadithRoute
    }
    '/emotions/': {
      id: '/emotions/'
      path: '/emotions'
      fullPath: '/emotions/'
      preLoaderRoute: typeof EmotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$id': {
      id: '/surah/$id'
      path: '/surah/$id'
      fullPath: '/surah/$id'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophets/$slug': {
      id: '/prophets/$slug'
      path: '/prophets/$slug'
      fullPath: '/prophets/$slug'
      preLoaderRoute: typeof ProphetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$slug': {
      id: '/plans/$slug'
      path: '/plans/$slug'
      fullPath: '/plans/$slug'
      preLoaderRoute: typeof PlansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/graph': {
      id: '/learn/graph'
      path: '/learn/graph'
      fullPath: '/learn/graph'
      preLoaderRoute: typeof LearnGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/hadith': {
      id: '/knowledge/hadith'
      path: '/knowledge/hadith'
      fullPath: '/knowledge/hadith'
      preLoaderRoute: typeof KnowledgeHadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/topics': {
      id: '/hadith/topics'
      path: '/topics'
      fullPath: '/hadith/topics'
      preLoaderRoute: typeof HadithTopicsRouteImport
      parentRoute: typeof HadithRoute
    }
    '/hadith/narrators': {
      id: '/hadith/narrators'
      path: '/narrators'
      fullPath: '/hadith/narrators'
      preLoaderRoute: typeof HadithNarratorsRouteImport
      parentRoute: typeof HadithRoute
    }
    '/hadith/muslim': {
      id: '/hadith/muslim'
      path: '/muslim'
      fullPath: '/hadith/muslim'
      preLoaderRoute: typeof HadithMuslimRouteImport
      parentRoute: typeof HadithRoute
    }
    '/hadith/bukhari': {
      id: '/hadith/bukhari'
      path: '/bukhari'
      fullPath: '/hadith/bukhari'
      preLoaderRoute: typeof HadithBukhariRouteImport
      parentRoute: typeof HadithRoute
    }
    '/hadith/$collection': {
      id: '/hadith/$collection'
      path: '/$collection'
      fullPath: '/hadith/$collection'
      preLoaderRoute: typeof HadithCollectionRouteImport
      parentRoute: typeof HadithRoute
    }
    '/explore/timeline': {
      id: '/explore/timeline'
      path: '/explore/timeline'
      fullPath: '/explore/timeline'
      preLoaderRoute: typeof ExploreTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/map': {
      id: '/explore/map'
      path: '/explore/map'
      fullPath: '/explore/map'
      preLoaderRoute: typeof ExploreMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotions/$slug': {
      id: '/emotions/$slug'
      path: '/emotions/$slug'
      fullPath: '/emotions/$slug'
      preLoaderRoute: typeof EmotionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/journeys/': {
      id: '/learn/journeys/'
      path: '/learn/journeys'
      fullPath: '/learn/journeys/'
      preLoaderRoute: typeof LearnJourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/learn/journeys/$slug': {
      id: '/learn/journeys/$slug'
      path: '/learn/journeys/$slug'
      fullPath: '/learn/journeys/$slug'
      preLoaderRoute: typeof LearnJourneysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$kind/$slug': {
      id: '/learn/$kind/$slug'
      path: '/learn/$kind/$slug'
      fullPath: '/learn/$kind/$slug'
      preLoaderRoute: typeof LearnKindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/$collection/$num': {
      id: '/hadith/$collection/$num'
      path: '/$num'
      fullPath: '/hadith/$collection/$num'
      preLoaderRoute: typeof HadithCollectionNumRouteImport
      parentRoute: typeof HadithCollectionRoute
    }
    '/hadith/$collection/$book': {
      id: '/hadith/$collection/$book'
      path: '/$book'
      fullPath: '/hadith/$collection/$book'
      preLoaderRoute: typeof HadithCollectionBookRouteImport
      parentRoute: typeof HadithCollectionRoute
    }
    '/api/public/seed-knowledge': {
      id: '/api/public/seed-knowledge'
      path: '/api/public/seed-knowledge'
      fullPath: '/api/public/seed-knowledge'
      preLoaderRoute: typeof ApiPublicSeedKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/translate-tafsir-hebrew': {
      id: '/api/public/admin/translate-tafsir-hebrew'
      path: '/api/public/admin/translate-tafsir-hebrew'
      fullPath: '/api/public/admin/translate-tafsir-hebrew'
      preLoaderRoute: typeof ApiPublicAdminTranslateTafsirHebrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/rebuild-grounded-index': {
      id: '/api/public/admin/rebuild-grounded-index'
      path: '/api/public/admin/rebuild-grounded-index'
      fullPath: '/api/public/admin/rebuild-grounded-index'
      preLoaderRoute: typeof ApiPublicAdminRebuildGroundedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/embed-hadith': {
      id: '/api/public/admin/embed-hadith'
      path: '/api/public/admin/embed-hadith'
      fullPath: '/api/public/admin/embed-hadith'
      preLoaderRoute: typeof ApiPublicAdminEmbedHadithRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HadithCollectionRouteChildren {
  HadithCollectionBookRoute: typeof HadithCollectionBookRoute
  HadithCollectionNumRoute: typeof HadithCollectionNumRoute
}

const HadithCollectionRouteChildren: HadithCollectionRouteChildren = {
  HadithCollectionBookRoute: HadithCollectionBookRoute,
  HadithCollectionNumRoute: HadithCollectionNumRoute,
}

const HadithCollectionRouteWithChildren =
  HadithCollectionRoute._addFileChildren(HadithCollectionRouteChildren)

interface HadithRouteChildren {
  HadithCollectionRoute: typeof HadithCollectionRouteWithChildren
  HadithBukhariRoute: typeof HadithBukhariRoute
  HadithMuslimRoute: typeof HadithMuslimRoute
  HadithNarratorsRoute: typeof HadithNarratorsRoute
  HadithTopicsRoute: typeof HadithTopicsRoute
  HadithIndexRoute: typeof HadithIndexRoute
}

const HadithRouteChildren: HadithRouteChildren = {
  HadithCollectionRoute: HadithCollectionRouteWithChildren,
  HadithBukhariRoute: HadithBukhariRoute,
  HadithMuslimRoute: HadithMuslimRoute,
  HadithNarratorsRoute: HadithNarratorsRoute,
  HadithTopicsRoute: HadithTopicsRoute,
  HadithIndexRoute: HadithIndexRoute,
}

const HadithRouteWithChildren =
  HadithRoute._addFileChildren(HadithRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  HadithRoute: HadithRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResearchRoute: ResearchRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EmotionsSlugRoute: EmotionsSlugRoute,
  ExploreMapRoute: ExploreMapRoute,
  ExploreTimelineRoute: ExploreTimelineRoute,
  KnowledgeHadithRoute: KnowledgeHadithRoute,
  LearnGraphRoute: LearnGraphRoute,
  PlansSlugRoute: PlansSlugRoute,
  ProphetsSlugRoute: ProphetsSlugRoute,
  SurahIdRoute: SurahIdRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  EmotionsIndexRoute: EmotionsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  ProphetsIndexRoute: ProphetsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  ApiPublicSeedKnowledgeRoute: ApiPublicSeedKnowledgeRoute,
  LearnKindSlugRoute: LearnKindSlugRoute,
  LearnJourneysSlugRoute: LearnJourneysSlugRoute,
  LearnJourneysIndexRoute: LearnJourneysIndexRoute,
  ApiPublicAdminEmbedHadithRoute: ApiPublicAdminEmbedHadithRoute,
  ApiPublicAdminRebuildGroundedIndexRoute:
    ApiPublicAdminRebuildGroundedIndexRoute,
  ApiPublicAdminTranslateTafsirHebrewRoute:
    ApiPublicAdminTranslateTafsirHebrewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
