/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RecentAiRouteImport } from './routes/recent-ai'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as SurahsIndexRouteImport } from './routes/surahs.index'
import { Route as ProphetsIndexRouteImport } from './routes/prophets.index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as HadithIndexRouteImport } from './routes/hadith.index'
import { Route as EmotionsIndexRouteImport } from './routes/emotions.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as SurahIdRouteImport } from './routes/surah.$id'
import { Route as ProphetsSlugRouteImport } from './routes/prophets.$slug'
import { Route as PlansSlugRouteImport } from './routes/plans.$slug'
import { Route as LearnTafsirIbnKathirRouteImport } from './routes/learn.tafsir-ibn-kathir'
import { Route as LearnGraphRouteImport } from './routes/learn.graph'
import { Route as KnowledgeHadithRouteImport } from './routes/knowledge.hadith'
import { Route as HadithTopicsRouteImport } from './routes/hadith.topics'
import { Route as HadithNarratorsRouteImport } from './routes/hadith.narrators'
import { Route as HadithCollectionRouteImport } from './routes/hadith.$collection'
import { Route as ExploreTimelineRouteImport } from './routes/explore.timeline'
import { Route as ExploreMapRouteImport } from './routes/explore.map'
import { Route as EmotionsSlugRouteImport } from './routes/emotions.$slug'
import { Route as LearnJourneysIndexRouteImport } from './routes/learn.journeys.index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections.index'
import { Route as LearnJourneysSlugRouteImport } from './routes/learn.journeys.$slug'
import { Route as LearnKindSlugRouteImport } from './routes/learn.$kind.$slug'
import { Route as HadithCollectionBookRouteImport } from './routes/hadith.$collection.$book'
import { Route as ApiPublicSurahNamesRouteImport } from './routes/api/public/surah-names'
import { Route as ApiPublicSeedKnowledgeRouteImport } from './routes/api/public/seed-knowledge'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminKidsRouteImport } from './routes/_authenticated/admin.kids'
import { Route as AuthenticatedAdminIngestRouteImport } from './routes/_authenticated/admin.ingest'
import { Route as AuthenticatedAdminHadithIngestRouteImport } from './routes/_authenticated/admin.hadith-ingest'
import { Route as AuthenticatedAdminHadithApiRouteImport } from './routes/_authenticated/admin.hadith-api'
import { Route as AuthenticatedAdminBackfillRouteImport } from './routes/_authenticated/admin.backfill'
import { Route as HadithCollectionEntryNumRouteImport } from './routes/hadith.$collection.entry.$num'
import { Route as ApiPublicAdminTranslateTafsirHebrewRouteImport } from './routes/api/public/admin/translate-tafsir-hebrew'
import { Route as ApiPublicAdminTranslateTafsirEnglishRouteImport } from './routes/api/public/admin/translate-tafsir-english'
import { Route as ApiPublicAdminTranslateHadithHebrewRouteImport } from './routes/api/public/admin/translate-hadith-hebrew'
import { Route as ApiPublicAdminRebuildGroundedIndexRouteImport } from './routes/api/public/admin/rebuild-grounded-index'
import { Route as ApiPublicAdminLinkHadithGraphRouteImport } from './routes/api/public/admin/link-hadith-graph'
import { Route as ApiPublicAdminIngestQuranJsonRouteImport } from './routes/api/public/admin/ingest-quran-json'
import { Route as ApiPublicAdminEmbedHadithRouteImport } from './routes/api/public/admin/embed-hadith'
import { Route as ApiPublicAdminBackfillVerseTranslationsRouteImport } from './routes/api/public/admin/backfill-verse-translations'
import { Route as ApiPublicAdminBackfillQuranChaptersRouteImport } from './routes/api/public/admin/backfill-quran-chapters'
import { Route as ApiPublicAdminBackfillAsbabNuzulRouteImport } from './routes/api/public/admin/backfill-asbab-nuzul'
import { Route as ApiPublicAdminBackfillArabicAyatRouteImport } from './routes/api/public/admin/backfill-arabic-ayat'
import { Route as ApiPublicAdminIngestQuranJsonIdRouteImport } from './routes/api/public/admin/ingest-quran-json.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/research.lazy').then((d) => d.Route))
const RecentAiRoute = RecentAiRouteImport.update({
  id: '/recent-ai',
  path: '/recent-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ask.lazy').then((d) => d.Route))
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahsIndexRoute = SurahsIndexRouteImport.update({
  id: '/surahs/',
  path: '/surahs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphetsIndexRoute = ProphetsIndexRouteImport.update({
  id: '/prophets/',
  path: '/prophets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithIndexRoute = HadithIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HadithRoute,
} as any)
const EmotionsIndexRoute = EmotionsIndexRouteImport.update({
  id: '/emotions/',
  path: '/emotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/surah/$id',
  path: '/surah/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphetsSlugRoute = ProphetsSlugRouteImport.update({
  id: '/prophets/$slug',
  path: '/prophets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansSlugRoute = PlansSlugRouteImport.update({
  id: '/plans/$slug',
  path: '/plans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTafsirIbnKathirRoute = LearnTafsirIbnKathirRouteImport.update({
  id: '/learn/tafsir-ibn-kathir',
  path: '/learn/tafsir-ibn-kathir',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGraphRoute = LearnGraphRouteImport.update({
  id: '/learn/graph',
  path: '/learn/graph',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/learn.graph.lazy').then((d) => d.Route))
const KnowledgeHadithRoute = KnowledgeHadithRouteImport.update({
  id: '/knowledge/hadith',
  path: '/knowledge/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithTopicsRoute = HadithTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => HadithRoute,
} as any)
const HadithNarratorsRoute = HadithNarratorsRouteImport.update({
  id: '/narrators',
  path: '/narrators',
  getParentRoute: () => HadithRoute,
} as any)
const HadithCollectionRoute = HadithCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => HadithRoute,
} as any)
const ExploreTimelineRoute = ExploreTimelineRouteImport.update({
  id: '/explore/timeline',
  path: '/explore/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMapRoute = ExploreMapRouteImport.update({
  id: '/explore/map',
  path: '/explore/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionsSlugRoute = EmotionsSlugRouteImport.update({
  id: '/emotions/$slug',
  path: '/emotions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJourneysIndexRoute = LearnJourneysIndexRouteImport.update({
  id: '/learn/journeys/',
  path: '/learn/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LearnJourneysSlugRoute = LearnJourneysSlugRouteImport.update({
  id: '/learn/journeys/$slug',
  path: '/learn/journeys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnKindSlugRoute = LearnKindSlugRouteImport.update({
  id: '/learn/$kind/$slug',
  path: '/learn/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithCollectionBookRoute = HadithCollectionBookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => HadithCollectionRoute,
} as any)
const ApiPublicSurahNamesRoute = ApiPublicSurahNamesRouteImport.update({
  id: '/api/public/surah-names',
  path: '/api/public/surah-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedKnowledgeRoute = ApiPublicSeedKnowledgeRouteImport.update({
  id: '/api/public/seed-knowledge',
  path: '/api/public/seed-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminKidsRoute = AuthenticatedAdminKidsRouteImport.update({
  id: '/admin/kids',
  path: '/admin/kids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIngestRoute =
  AuthenticatedAdminIngestRouteImport.update({
    id: '/admin/ingest',
    path: '/admin/ingest',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHadithIngestRoute =
  AuthenticatedAdminHadithIngestRouteImport.update({
    id: '/admin/hadith-ingest',
    path: '/admin/hadith-ingest',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHadithApiRoute =
  AuthenticatedAdminHadithApiRouteImport.update({
    id: '/admin/hadith-api',
    path: '/admin/hadith-api',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBackfillRoute =
  AuthenticatedAdminBackfillRouteImport.update({
    id: '/admin/backfill',
    path: '/admin/backfill',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const HadithCollectionEntryNumRoute =
  HadithCollectionEntryNumRouteImport.update({
    id: '/entry/$num',
    path: '/entry/$num',
    getParentRoute: () => HadithCollectionRoute,
  } as any)
const ApiPublicAdminTranslateTafsirHebrewRoute =
  ApiPublicAdminTranslateTafsirHebrewRouteImport.update({
    id: '/api/public/admin/translate-tafsir-hebrew',
    path: '/api/public/admin/translate-tafsir-hebrew',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminTranslateTafsirEnglishRoute =
  ApiPublicAdminTranslateTafsirEnglishRouteImport.update({
    id: '/api/public/admin/translate-tafsir-english',
    path: '/api/public/admin/translate-tafsir-english',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminTranslateHadithHebrewRoute =
  ApiPublicAdminTranslateHadithHebrewRouteImport.update({
    id: '/api/public/admin/translate-hadith-hebrew',
    path: '/api/public/admin/translate-hadith-hebrew',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminRebuildGroundedIndexRoute =
  ApiPublicAdminRebuildGroundedIndexRouteImport.update({
    id: '/api/public/admin/rebuild-grounded-index',
    path: '/api/public/admin/rebuild-grounded-index',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminLinkHadithGraphRoute =
  ApiPublicAdminLinkHadithGraphRouteImport.update({
    id: '/api/public/admin/link-hadith-graph',
    path: '/api/public/admin/link-hadith-graph',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminIngestQuranJsonRoute =
  ApiPublicAdminIngestQuranJsonRouteImport.update({
    id: '/api/public/admin/ingest-quran-json',
    path: '/api/public/admin/ingest-quran-json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminEmbedHadithRoute =
  ApiPublicAdminEmbedHadithRouteImport.update({
    id: '/api/public/admin/embed-hadith',
    path: '/api/public/admin/embed-hadith',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBackfillVerseTranslationsRoute =
  ApiPublicAdminBackfillVerseTranslationsRouteImport.update({
    id: '/api/public/admin/backfill-verse-translations',
    path: '/api/public/admin/backfill-verse-translations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBackfillQuranChaptersRoute =
  ApiPublicAdminBackfillQuranChaptersRouteImport.update({
    id: '/api/public/admin/backfill-quran-chapters',
    path: '/api/public/admin/backfill-quran-chapters',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBackfillAsbabNuzulRoute =
  ApiPublicAdminBackfillAsbabNuzulRouteImport.update({
    id: '/api/public/admin/backfill-asbab-nuzul',
    path: '/api/public/admin/backfill-asbab-nuzul',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBackfillArabicAyatRoute =
  ApiPublicAdminBackfillArabicAyatRouteImport.update({
    id: '/api/public/admin/backfill-arabic-ayat',
    path: '/api/public/admin/backfill-arabic-ayat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminIngestQuranJsonIdRoute =
  ApiPublicAdminIngestQuranJsonIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicAdminIngestQuranJsonRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRouteWithChildren
  '/kids': typeof KidsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recent-ai': typeof RecentAiRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emotions/$slug': typeof EmotionsSlugRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/timeline': typeof ExploreTimelineRoute
  '/hadith/$collection': typeof HadithCollectionRouteWithChildren
  '/hadith/narrators': typeof HadithNarratorsRoute
  '/hadith/topics': typeof HadithTopicsRoute
  '/knowledge/hadith': typeof KnowledgeHadithRoute
  '/learn/graph': typeof LearnGraphRoute
  '/learn/tafsir-ibn-kathir': typeof LearnTafsirIbnKathirRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/prophets/$slug': typeof ProphetsSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/emotions/': typeof EmotionsIndexRoute
  '/hadith/': typeof HadithIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/prophets/': typeof ProphetsIndexRoute
  '/surahs/': typeof SurahsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/admin/backfill': typeof AuthenticatedAdminBackfillRoute
  '/admin/hadith-api': typeof AuthenticatedAdminHadithApiRoute
  '/admin/hadith-ingest': typeof AuthenticatedAdminHadithIngestRoute
  '/admin/ingest': typeof AuthenticatedAdminIngestRoute
  '/admin/kids': typeof AuthenticatedAdminKidsRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
  '/api/public/surah-names': typeof ApiPublicSurahNamesRoute
  '/hadith/$collection/$book': typeof HadithCollectionBookRoute
  '/learn/$kind/$slug': typeof LearnKindSlugRoute
  '/learn/journeys/$slug': typeof LearnJourneysSlugRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/learn/journeys/': typeof LearnJourneysIndexRoute
  '/api/public/admin/backfill-arabic-ayat': typeof ApiPublicAdminBackfillArabicAyatRoute
  '/api/public/admin/backfill-asbab-nuzul': typeof ApiPublicAdminBackfillAsbabNuzulRoute
  '/api/public/admin/backfill-quran-chapters': typeof ApiPublicAdminBackfillQuranChaptersRoute
  '/api/public/admin/backfill-verse-translations': typeof ApiPublicAdminBackfillVerseTranslationsRoute
  '/api/public/admin/embed-hadith': typeof ApiPublicAdminEmbedHadithRoute
  '/api/public/admin/ingest-quran-json': typeof ApiPublicAdminIngestQuranJsonRouteWithChildren
  '/api/public/admin/link-hadith-graph': typeof ApiPublicAdminLinkHadithGraphRoute
  '/api/public/admin/rebuild-grounded-index': typeof ApiPublicAdminRebuildGroundedIndexRoute
  '/api/public/admin/translate-hadith-hebrew': typeof ApiPublicAdminTranslateHadithHebrewRoute
  '/api/public/admin/translate-tafsir-english': typeof ApiPublicAdminTranslateTafsirEnglishRoute
  '/api/public/admin/translate-tafsir-hebrew': typeof ApiPublicAdminTranslateTafsirHebrewRoute
  '/hadith/$collection/entry/$num': typeof HadithCollectionEntryNumRoute
  '/api/public/admin/ingest-quran-json/$id': typeof ApiPublicAdminIngestQuranJsonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/kids': typeof KidsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recent-ai': typeof RecentAiRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emotions/$slug': typeof EmotionsSlugRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/timeline': typeof ExploreTimelineRoute
  '/hadith/$collection': typeof HadithCollectionRouteWithChildren
  '/hadith/narrators': typeof HadithNarratorsRoute
  '/hadith/topics': typeof HadithTopicsRoute
  '/knowledge/hadith': typeof KnowledgeHadithRoute
  '/learn/graph': typeof LearnGraphRoute
  '/learn/tafsir-ibn-kathir': typeof LearnTafsirIbnKathirRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/prophets/$slug': typeof ProphetsSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/emotions': typeof EmotionsIndexRoute
  '/hadith': typeof HadithIndexRoute
  '/learn': typeof LearnIndexRoute
  '/plans': typeof PlansIndexRoute
  '/prophets': typeof ProphetsIndexRoute
  '/surahs': typeof SurahsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/admin/backfill': typeof AuthenticatedAdminBackfillRoute
  '/admin/hadith-api': typeof AuthenticatedAdminHadithApiRoute
  '/admin/hadith-ingest': typeof AuthenticatedAdminHadithIngestRoute
  '/admin/ingest': typeof AuthenticatedAdminIngestRoute
  '/admin/kids': typeof AuthenticatedAdminKidsRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
  '/api/public/surah-names': typeof ApiPublicSurahNamesRoute
  '/hadith/$collection/$book': typeof HadithCollectionBookRoute
  '/learn/$kind/$slug': typeof LearnKindSlugRoute
  '/learn/journeys/$slug': typeof LearnJourneysSlugRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/learn/journeys': typeof LearnJourneysIndexRoute
  '/api/public/admin/backfill-arabic-ayat': typeof ApiPublicAdminBackfillArabicAyatRoute
  '/api/public/admin/backfill-asbab-nuzul': typeof ApiPublicAdminBackfillAsbabNuzulRoute
  '/api/public/admin/backfill-quran-chapters': typeof ApiPublicAdminBackfillQuranChaptersRoute
  '/api/public/admin/backfill-verse-translations': typeof ApiPublicAdminBackfillVerseTranslationsRoute
  '/api/public/admin/embed-hadith': typeof ApiPublicAdminEmbedHadithRoute
  '/api/public/admin/ingest-quran-json': typeof ApiPublicAdminIngestQuranJsonRouteWithChildren
  '/api/public/admin/link-hadith-graph': typeof ApiPublicAdminLinkHadithGraphRoute
  '/api/public/admin/rebuild-grounded-index': typeof ApiPublicAdminRebuildGroundedIndexRoute
  '/api/public/admin/translate-hadith-hebrew': typeof ApiPublicAdminTranslateHadithHebrewRoute
  '/api/public/admin/translate-tafsir-english': typeof ApiPublicAdminTranslateTafsirEnglishRoute
  '/api/public/admin/translate-tafsir-hebrew': typeof ApiPublicAdminTranslateTafsirHebrewRoute
  '/hadith/$collection/entry/$num': typeof HadithCollectionEntryNumRoute
  '/api/public/admin/ingest-quran-json/$id': typeof ApiPublicAdminIngestQuranJsonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRouteWithChildren
  '/kids': typeof KidsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recent-ai': typeof RecentAiRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emotions/$slug': typeof EmotionsSlugRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/timeline': typeof ExploreTimelineRoute
  '/hadith/$collection': typeof HadithCollectionRouteWithChildren
  '/hadith/narrators': typeof HadithNarratorsRoute
  '/hadith/topics': typeof HadithTopicsRoute
  '/knowledge/hadith': typeof KnowledgeHadithRoute
  '/learn/graph': typeof LearnGraphRoute
  '/learn/tafsir-ibn-kathir': typeof LearnTafsirIbnKathirRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/prophets/$slug': typeof ProphetsSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/emotions/': typeof EmotionsIndexRoute
  '/hadith/': typeof HadithIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/prophets/': typeof ProphetsIndexRoute
  '/surahs/': typeof SurahsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/_authenticated/admin/backfill': typeof AuthenticatedAdminBackfillRoute
  '/_authenticated/admin/hadith-api': typeof AuthenticatedAdminHadithApiRoute
  '/_authenticated/admin/hadith-ingest': typeof AuthenticatedAdminHadithIngestRoute
  '/_authenticated/admin/ingest': typeof AuthenticatedAdminIngestRoute
  '/_authenticated/admin/kids': typeof AuthenticatedAdminKidsRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
  '/api/public/surah-names': typeof ApiPublicSurahNamesRoute
  '/hadith/$collection/$book': typeof HadithCollectionBookRoute
  '/learn/$kind/$slug': typeof LearnKindSlugRoute
  '/learn/journeys/$slug': typeof LearnJourneysSlugRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/learn/journeys/': typeof LearnJourneysIndexRoute
  '/api/public/admin/backfill-arabic-ayat': typeof ApiPublicAdminBackfillArabicAyatRoute
  '/api/public/admin/backfill-asbab-nuzul': typeof ApiPublicAdminBackfillAsbabNuzulRoute
  '/api/public/admin/backfill-quran-chapters': typeof ApiPublicAdminBackfillQuranChaptersRoute
  '/api/public/admin/backfill-verse-translations': typeof ApiPublicAdminBackfillVerseTranslationsRoute
  '/api/public/admin/embed-hadith': typeof ApiPublicAdminEmbedHadithRoute
  '/api/public/admin/ingest-quran-json': typeof ApiPublicAdminIngestQuranJsonRouteWithChildren
  '/api/public/admin/link-hadith-graph': typeof ApiPublicAdminLinkHadithGraphRoute
  '/api/public/admin/rebuild-grounded-index': typeof ApiPublicAdminRebuildGroundedIndexRoute
  '/api/public/admin/translate-hadith-hebrew': typeof ApiPublicAdminTranslateHadithHebrewRoute
  '/api/public/admin/translate-tafsir-english': typeof ApiPublicAdminTranslateTafsirEnglishRoute
  '/api/public/admin/translate-tafsir-hebrew': typeof ApiPublicAdminTranslateTafsirHebrewRoute
  '/hadith/$collection/entry/$num': typeof HadithCollectionEntryNumRoute
  '/api/public/admin/ingest-quran-json/$id': typeof ApiPublicAdminIngestQuranJsonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth'
    | '/favorites'
    | '/hadith'
    | '/kids'
    | '/library'
    | '/onboarding'
    | '/profile'
    | '/recent-ai'
    | '/research'
    | '/search'
    | '/sitemap.xml'
    | '/emotions/$slug'
    | '/explore/map'
    | '/explore/timeline'
    | '/hadith/$collection'
    | '/hadith/narrators'
    | '/hadith/topics'
    | '/knowledge/hadith'
    | '/learn/graph'
    | '/learn/tafsir-ibn-kathir'
    | '/plans/$slug'
    | '/prophets/$slug'
    | '/surah/$id'
    | '/topics/$slug'
    | '/emotions/'
    | '/hadith/'
    | '/learn/'
    | '/plans/'
    | '/prophets/'
    | '/surahs/'
    | '/topics/'
    | '/admin/backfill'
    | '/admin/hadith-api'
    | '/admin/hadith-ingest'
    | '/admin/ingest'
    | '/admin/kids'
    | '/admin/setup'
    | '/api/public/seed-knowledge'
    | '/api/public/surah-names'
    | '/hadith/$collection/$book'
    | '/learn/$kind/$slug'
    | '/learn/journeys/$slug'
    | '/collections/'
    | '/learn/journeys/'
    | '/api/public/admin/backfill-arabic-ayat'
    | '/api/public/admin/backfill-asbab-nuzul'
    | '/api/public/admin/backfill-quran-chapters'
    | '/api/public/admin/backfill-verse-translations'
    | '/api/public/admin/embed-hadith'
    | '/api/public/admin/ingest-quran-json'
    | '/api/public/admin/link-hadith-graph'
    | '/api/public/admin/rebuild-grounded-index'
    | '/api/public/admin/translate-hadith-hebrew'
    | '/api/public/admin/translate-tafsir-english'
    | '/api/public/admin/translate-tafsir-hebrew'
    | '/hadith/$collection/entry/$num'
    | '/api/public/admin/ingest-quran-json/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth'
    | '/favorites'
    | '/kids'
    | '/library'
    | '/onboarding'
    | '/profile'
    | '/recent-ai'
    | '/research'
    | '/search'
    | '/sitemap.xml'
    | '/emotions/$slug'
    | '/explore/map'
    | '/explore/timeline'
    | '/hadith/$collection'
    | '/hadith/narrators'
    | '/hadith/topics'
    | '/knowledge/hadith'
    | '/learn/graph'
    | '/learn/tafsir-ibn-kathir'
    | '/plans/$slug'
    | '/prophets/$slug'
    | '/surah/$id'
    | '/topics/$slug'
    | '/emotions'
    | '/hadith'
    | '/learn'
    | '/plans'
    | '/prophets'
    | '/surahs'
    | '/topics'
    | '/admin/backfill'
    | '/admin/hadith-api'
    | '/admin/hadith-ingest'
    | '/admin/ingest'
    | '/admin/kids'
    | '/admin/setup'
    | '/api/public/seed-knowledge'
    | '/api/public/surah-names'
    | '/hadith/$collection/$book'
    | '/learn/$kind/$slug'
    | '/learn/journeys/$slug'
    | '/collections'
    | '/learn/journeys'
    | '/api/public/admin/backfill-arabic-ayat'
    | '/api/public/admin/backfill-asbab-nuzul'
    | '/api/public/admin/backfill-quran-chapters'
    | '/api/public/admin/backfill-verse-translations'
    | '/api/public/admin/embed-hadith'
    | '/api/public/admin/ingest-quran-json'
    | '/api/public/admin/link-hadith-graph'
    | '/api/public/admin/rebuild-grounded-index'
    | '/api/public/admin/translate-hadith-hebrew'
    | '/api/public/admin/translate-tafsir-english'
    | '/api/public/admin/translate-tafsir-hebrew'
    | '/hadith/$collection/entry/$num'
    | '/api/public/admin/ingest-quran-json/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ask'
    | '/auth'
    | '/favorites'
    | '/hadith'
    | '/kids'
    | '/library'
    | '/onboarding'
    | '/profile'
    | '/recent-ai'
    | '/research'
    | '/search'
    | '/sitemap.xml'
    | '/emotions/$slug'
    | '/explore/map'
    | '/explore/timeline'
    | '/hadith/$collection'
    | '/hadith/narrators'
    | '/hadith/topics'
    | '/knowledge/hadith'
    | '/learn/graph'
    | '/learn/tafsir-ibn-kathir'
    | '/plans/$slug'
    | '/prophets/$slug'
    | '/surah/$id'
    | '/topics/$slug'
    | '/emotions/'
    | '/hadith/'
    | '/learn/'
    | '/plans/'
    | '/prophets/'
    | '/surahs/'
    | '/topics/'
    | '/_authenticated/admin/backfill'
    | '/_authenticated/admin/hadith-api'
    | '/_authenticated/admin/hadith-ingest'
    | '/_authenticated/admin/ingest'
    | '/_authenticated/admin/kids'
    | '/_authenticated/admin/setup'
    | '/api/public/seed-knowledge'
    | '/api/public/surah-names'
    | '/hadith/$collection/$book'
    | '/learn/$kind/$slug'
    | '/learn/journeys/$slug'
    | '/_authenticated/collections/'
    | '/learn/journeys/'
    | '/api/public/admin/backfill-arabic-ayat'
    | '/api/public/admin/backfill-asbab-nuzul'
    | '/api/public/admin/backfill-quran-chapters'
    | '/api/public/admin/backfill-verse-translations'
    | '/api/public/admin/embed-hadith'
    | '/api/public/admin/ingest-quran-json'
    | '/api/public/admin/link-hadith-graph'
    | '/api/public/admin/rebuild-grounded-index'
    | '/api/public/admin/translate-hadith-hebrew'
    | '/api/public/admin/translate-tafsir-english'
    | '/api/public/admin/translate-tafsir-hebrew'
    | '/hadith/$collection/entry/$num'
    | '/api/public/admin/ingest-quran-json/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  HadithRoute: typeof HadithRouteWithChildren
  KidsRoute: typeof KidsRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RecentAiRoute: typeof RecentAiRoute
  ResearchRoute: typeof ResearchRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EmotionsSlugRoute: typeof EmotionsSlugRoute
  ExploreMapRoute: typeof ExploreMapRoute
  ExploreTimelineRoute: typeof ExploreTimelineRoute
  KnowledgeHadithRoute: typeof KnowledgeHadithRoute
  LearnGraphRoute: typeof LearnGraphRoute
  LearnTafsirIbnKathirRoute: typeof LearnTafsirIbnKathirRoute
  PlansSlugRoute: typeof PlansSlugRoute
  ProphetsSlugRoute: typeof ProphetsSlugRoute
  SurahIdRoute: typeof SurahIdRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  EmotionsIndexRoute: typeof EmotionsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  ProphetsIndexRoute: typeof ProphetsIndexRoute
  SurahsIndexRoute: typeof SurahsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  ApiPublicSeedKnowledgeRoute: typeof ApiPublicSeedKnowledgeRoute
  ApiPublicSurahNamesRoute: typeof ApiPublicSurahNamesRoute
  LearnKindSlugRoute: typeof LearnKindSlugRoute
  LearnJourneysSlugRoute: typeof LearnJourneysSlugRoute
  LearnJourneysIndexRoute: typeof LearnJourneysIndexRoute
  ApiPublicAdminBackfillArabicAyatRoute: typeof ApiPublicAdminBackfillArabicAyatRoute
  ApiPublicAdminBackfillAsbabNuzulRoute: typeof ApiPublicAdminBackfillAsbabNuzulRoute
  ApiPublicAdminBackfillQuranChaptersRoute: typeof ApiPublicAdminBackfillQuranChaptersRoute
  ApiPublicAdminBackfillVerseTranslationsRoute: typeof ApiPublicAdminBackfillVerseTranslationsRoute
  ApiPublicAdminEmbedHadithRoute: typeof ApiPublicAdminEmbedHadithRoute
  ApiPublicAdminIngestQuranJsonRoute: typeof ApiPublicAdminIngestQuranJsonRouteWithChildren
  ApiPublicAdminLinkHadithGraphRoute: typeof ApiPublicAdminLinkHadithGraphRoute
  ApiPublicAdminRebuildGroundedIndexRoute: typeof ApiPublicAdminRebuildGroundedIndexRoute
  ApiPublicAdminTranslateHadithHebrewRoute: typeof ApiPublicAdminTranslateHadithHebrewRoute
  ApiPublicAdminTranslateTafsirEnglishRoute: typeof ApiPublicAdminTranslateTafsirEnglishRoute
  ApiPublicAdminTranslateTafsirHebrewRoute: typeof ApiPublicAdminTranslateTafsirHebrewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-ai': {
      id: '/recent-ai'
      path: '/recent-ai'
      fullPath: '/recent-ai'
      preLoaderRoute: typeof RecentAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surahs/': {
      id: '/surahs/'
      path: '/surahs'
      fullPath: '/surahs/'
      preLoaderRoute: typeof SurahsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophets/': {
      id: '/prophets/'
      path: '/prophets'
      fullPath: '/prophets/'
      preLoaderRoute: typeof ProphetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/': {
      id: '/hadith/'
      path: '/'
      fullPath: '/hadith/'
      preLoaderRoute: typeof HadithIndexRouteImport
      parentRoute: typeof HadithRoute
    }
    '/emotions/': {
      id: '/emotions/'
      path: '/emotions'
      fullPath: '/emotions/'
      preLoaderRoute: typeof EmotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$id': {
      id: '/surah/$id'
      path: '/surah/$id'
      fullPath: '/surah/$id'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophets/$slug': {
      id: '/prophets/$slug'
      path: '/prophets/$slug'
      fullPath: '/prophets/$slug'
      preLoaderRoute: typeof ProphetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$slug': {
      id: '/plans/$slug'
      path: '/plans/$slug'
      fullPath: '/plans/$slug'
      preLoaderRoute: typeof PlansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/tafsir-ibn-kathir': {
      id: '/learn/tafsir-ibn-kathir'
      path: '/learn/tafsir-ibn-kathir'
      fullPath: '/learn/tafsir-ibn-kathir'
      preLoaderRoute: typeof LearnTafsirIbnKathirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/graph': {
      id: '/learn/graph'
      path: '/learn/graph'
      fullPath: '/learn/graph'
      preLoaderRoute: typeof LearnGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/hadith': {
      id: '/knowledge/hadith'
      path: '/knowledge/hadith'
      fullPath: '/knowledge/hadith'
      preLoaderRoute: typeof KnowledgeHadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/topics': {
      id: '/hadith/topics'
      path: '/topics'
      fullPath: '/hadith/topics'
      preLoaderRoute: typeof HadithTopicsRouteImport
      parentRoute: typeof HadithRoute
    }
    '/hadith/narrators': {
      id: '/hadith/narrators'
      path: '/narrators'
      fullPath: '/hadith/narrators'
      preLoaderRoute: typeof HadithNarratorsRouteImport
      parentRoute: typeof HadithRoute
    }
    '/hadith/$collection': {
      id: '/hadith/$collection'
      path: '/$collection'
      fullPath: '/hadith/$collection'
      preLoaderRoute: typeof HadithCollectionRouteImport
      parentRoute: typeof HadithRoute
    }
    '/explore/timeline': {
      id: '/explore/timeline'
      path: '/explore/timeline'
      fullPath: '/explore/timeline'
      preLoaderRoute: typeof ExploreTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/map': {
      id: '/explore/map'
      path: '/explore/map'
      fullPath: '/explore/map'
      preLoaderRoute: typeof ExploreMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotions/$slug': {
      id: '/emotions/$slug'
      path: '/emotions/$slug'
      fullPath: '/emotions/$slug'
      preLoaderRoute: typeof EmotionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/journeys/': {
      id: '/learn/journeys/'
      path: '/learn/journeys'
      fullPath: '/learn/journeys/'
      preLoaderRoute: typeof LearnJourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/learn/journeys/$slug': {
      id: '/learn/journeys/$slug'
      path: '/learn/journeys/$slug'
      fullPath: '/learn/journeys/$slug'
      preLoaderRoute: typeof LearnJourneysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$kind/$slug': {
      id: '/learn/$kind/$slug'
      path: '/learn/$kind/$slug'
      fullPath: '/learn/$kind/$slug'
      preLoaderRoute: typeof LearnKindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/$collection/$book': {
      id: '/hadith/$collection/$book'
      path: '/$book'
      fullPath: '/hadith/$collection/$book'
      preLoaderRoute: typeof HadithCollectionBookRouteImport
      parentRoute: typeof HadithCollectionRoute
    }
    '/api/public/surah-names': {
      id: '/api/public/surah-names'
      path: '/api/public/surah-names'
      fullPath: '/api/public/surah-names'
      preLoaderRoute: typeof ApiPublicSurahNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-knowledge': {
      id: '/api/public/seed-knowledge'
      path: '/api/public/seed-knowledge'
      fullPath: '/api/public/seed-knowledge'
      preLoaderRoute: typeof ApiPublicSeedKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kids': {
      id: '/_authenticated/admin/kids'
      path: '/admin/kids'
      fullPath: '/admin/kids'
      preLoaderRoute: typeof AuthenticatedAdminKidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ingest': {
      id: '/_authenticated/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AuthenticatedAdminIngestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hadith-ingest': {
      id: '/_authenticated/admin/hadith-ingest'
      path: '/admin/hadith-ingest'
      fullPath: '/admin/hadith-ingest'
      preLoaderRoute: typeof AuthenticatedAdminHadithIngestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hadith-api': {
      id: '/_authenticated/admin/hadith-api'
      path: '/admin/hadith-api'
      fullPath: '/admin/hadith-api'
      preLoaderRoute: typeof AuthenticatedAdminHadithApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/backfill': {
      id: '/_authenticated/admin/backfill'
      path: '/admin/backfill'
      fullPath: '/admin/backfill'
      preLoaderRoute: typeof AuthenticatedAdminBackfillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/hadith/$collection/entry/$num': {
      id: '/hadith/$collection/entry/$num'
      path: '/entry/$num'
      fullPath: '/hadith/$collection/entry/$num'
      preLoaderRoute: typeof HadithCollectionEntryNumRouteImport
      parentRoute: typeof HadithCollectionRoute
    }
    '/api/public/admin/translate-tafsir-hebrew': {
      id: '/api/public/admin/translate-tafsir-hebrew'
      path: '/api/public/admin/translate-tafsir-hebrew'
      fullPath: '/api/public/admin/translate-tafsir-hebrew'
      preLoaderRoute: typeof ApiPublicAdminTranslateTafsirHebrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/translate-tafsir-english': {
      id: '/api/public/admin/translate-tafsir-english'
      path: '/api/public/admin/translate-tafsir-english'
      fullPath: '/api/public/admin/translate-tafsir-english'
      preLoaderRoute: typeof ApiPublicAdminTranslateTafsirEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/translate-hadith-hebrew': {
      id: '/api/public/admin/translate-hadith-hebrew'
      path: '/api/public/admin/translate-hadith-hebrew'
      fullPath: '/api/public/admin/translate-hadith-hebrew'
      preLoaderRoute: typeof ApiPublicAdminTranslateHadithHebrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/rebuild-grounded-index': {
      id: '/api/public/admin/rebuild-grounded-index'
      path: '/api/public/admin/rebuild-grounded-index'
      fullPath: '/api/public/admin/rebuild-grounded-index'
      preLoaderRoute: typeof ApiPublicAdminRebuildGroundedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/link-hadith-graph': {
      id: '/api/public/admin/link-hadith-graph'
      path: '/api/public/admin/link-hadith-graph'
      fullPath: '/api/public/admin/link-hadith-graph'
      preLoaderRoute: typeof ApiPublicAdminLinkHadithGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/ingest-quran-json': {
      id: '/api/public/admin/ingest-quran-json'
      path: '/api/public/admin/ingest-quran-json'
      fullPath: '/api/public/admin/ingest-quran-json'
      preLoaderRoute: typeof ApiPublicAdminIngestQuranJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/embed-hadith': {
      id: '/api/public/admin/embed-hadith'
      path: '/api/public/admin/embed-hadith'
      fullPath: '/api/public/admin/embed-hadith'
      preLoaderRoute: typeof ApiPublicAdminEmbedHadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/backfill-verse-translations': {
      id: '/api/public/admin/backfill-verse-translations'
      path: '/api/public/admin/backfill-verse-translations'
      fullPath: '/api/public/admin/backfill-verse-translations'
      preLoaderRoute: typeof ApiPublicAdminBackfillVerseTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/backfill-quran-chapters': {
      id: '/api/public/admin/backfill-quran-chapters'
      path: '/api/public/admin/backfill-quran-chapters'
      fullPath: '/api/public/admin/backfill-quran-chapters'
      preLoaderRoute: typeof ApiPublicAdminBackfillQuranChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/backfill-asbab-nuzul': {
      id: '/api/public/admin/backfill-asbab-nuzul'
      path: '/api/public/admin/backfill-asbab-nuzul'
      fullPath: '/api/public/admin/backfill-asbab-nuzul'
      preLoaderRoute: typeof ApiPublicAdminBackfillAsbabNuzulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/backfill-arabic-ayat': {
      id: '/api/public/admin/backfill-arabic-ayat'
      path: '/api/public/admin/backfill-arabic-ayat'
      fullPath: '/api/public/admin/backfill-arabic-ayat'
      preLoaderRoute: typeof ApiPublicAdminBackfillArabicAyatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/ingest-quran-json/$id': {
      id: '/api/public/admin/ingest-quran-json/$id'
      path: '/$id'
      fullPath: '/api/public/admin/ingest-quran-json/$id'
      preLoaderRoute: typeof ApiPublicAdminIngestQuranJsonIdRouteImport
      parentRoute: typeof ApiPublicAdminIngestQuranJsonRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBackfillRoute: typeof AuthenticatedAdminBackfillRoute
  AuthenticatedAdminHadithApiRoute: typeof AuthenticatedAdminHadithApiRoute
  AuthenticatedAdminHadithIngestRoute: typeof AuthenticatedAdminHadithIngestRoute
  AuthenticatedAdminIngestRoute: typeof AuthenticatedAdminIngestRoute
  AuthenticatedAdminKidsRoute: typeof AuthenticatedAdminKidsRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBackfillRoute: AuthenticatedAdminBackfillRoute,
  AuthenticatedAdminHadithApiRoute: AuthenticatedAdminHadithApiRoute,
  AuthenticatedAdminHadithIngestRoute: AuthenticatedAdminHadithIngestRoute,
  AuthenticatedAdminIngestRoute: AuthenticatedAdminIngestRoute,
  AuthenticatedAdminKidsRoute: AuthenticatedAdminKidsRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HadithCollectionRouteChildren {
  HadithCollectionBookRoute: typeof HadithCollectionBookRoute
  HadithCollectionEntryNumRoute: typeof HadithCollectionEntryNumRoute
}

const HadithCollectionRouteChildren: HadithCollectionRouteChildren = {
  HadithCollectionBookRoute: HadithCollectionBookRoute,
  HadithCollectionEntryNumRoute: HadithCollectionEntryNumRoute,
}

const HadithCollectionRouteWithChildren =
  HadithCollectionRoute._addFileChildren(HadithCollectionRouteChildren)

interface HadithRouteChildren {
  HadithCollectionRoute: typeof HadithCollectionRouteWithChildren
  HadithNarratorsRoute: typeof HadithNarratorsRoute
  HadithTopicsRoute: typeof HadithTopicsRoute
  HadithIndexRoute: typeof HadithIndexRoute
}

const HadithRouteChildren: HadithRouteChildren = {
  HadithCollectionRoute: HadithCollectionRouteWithChildren,
  HadithNarratorsRoute: HadithNarratorsRoute,
  HadithTopicsRoute: HadithTopicsRoute,
  HadithIndexRoute: HadithIndexRoute,
}

const HadithRouteWithChildren =
  HadithRoute._addFileChildren(HadithRouteChildren)

interface ApiPublicAdminIngestQuranJsonRouteChildren {
  ApiPublicAdminIngestQuranJsonIdRoute: typeof ApiPublicAdminIngestQuranJsonIdRoute
}

const ApiPublicAdminIngestQuranJsonRouteChildren: ApiPublicAdminIngestQuranJsonRouteChildren =
  {
    ApiPublicAdminIngestQuranJsonIdRoute: ApiPublicAdminIngestQuranJsonIdRoute,
  }

const ApiPublicAdminIngestQuranJsonRouteWithChildren =
  ApiPublicAdminIngestQuranJsonRoute._addFileChildren(
    ApiPublicAdminIngestQuranJsonRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  HadithRoute: HadithRouteWithChildren,
  KidsRoute: KidsRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RecentAiRoute: RecentAiRoute,
  ResearchRoute: ResearchRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EmotionsSlugRoute: EmotionsSlugRoute,
  ExploreMapRoute: ExploreMapRoute,
  ExploreTimelineRoute: ExploreTimelineRoute,
  KnowledgeHadithRoute: KnowledgeHadithRoute,
  LearnGraphRoute: LearnGraphRoute,
  LearnTafsirIbnKathirRoute: LearnTafsirIbnKathirRoute,
  PlansSlugRoute: PlansSlugRoute,
  ProphetsSlugRoute: ProphetsSlugRoute,
  SurahIdRoute: SurahIdRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  EmotionsIndexRoute: EmotionsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  ProphetsIndexRoute: ProphetsIndexRoute,
  SurahsIndexRoute: SurahsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  ApiPublicSeedKnowledgeRoute: ApiPublicSeedKnowledgeRoute,
  ApiPublicSurahNamesRoute: ApiPublicSurahNamesRoute,
  LearnKindSlugRoute: LearnKindSlugRoute,
  LearnJourneysSlugRoute: LearnJourneysSlugRoute,
  LearnJourneysIndexRoute: LearnJourneysIndexRoute,
  ApiPublicAdminBackfillArabicAyatRoute: ApiPublicAdminBackfillArabicAyatRoute,
  ApiPublicAdminBackfillAsbabNuzulRoute: ApiPublicAdminBackfillAsbabNuzulRoute,
  ApiPublicAdminBackfillQuranChaptersRoute:
    ApiPublicAdminBackfillQuranChaptersRoute,
  ApiPublicAdminBackfillVerseTranslationsRoute:
    ApiPublicAdminBackfillVerseTranslationsRoute,
  ApiPublicAdminEmbedHadithRoute: ApiPublicAdminEmbedHadithRoute,
  ApiPublicAdminIngestQuranJsonRoute:
    ApiPublicAdminIngestQuranJsonRouteWithChildren,
  ApiPublicAdminLinkHadithGraphRoute: ApiPublicAdminLinkHadithGraphRoute,
  ApiPublicAdminRebuildGroundedIndexRoute:
    ApiPublicAdminRebuildGroundedIndexRoute,
  ApiPublicAdminTranslateHadithHebrewRoute:
    ApiPublicAdminTranslateHadithHebrewRoute,
  ApiPublicAdminTranslateTafsirEnglishRoute:
    ApiPublicAdminTranslateTafsirEnglishRoute,
  ApiPublicAdminTranslateTafsirHebrewRoute:
    ApiPublicAdminTranslateTafsirHebrewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
